# Generated by Django 2.2.1 on 2019-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='forSale',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('streetName', 'houseNumber', 'city', 'postalCode')},
        ),
    ]
