# Generated by Django 2.2.1 on 2019-05-16 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apartments', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('searchItem', 'userID')},
        ),
    ]
