# Generated by Django 2.2.1 on 2019-05-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0005_auto_20190516_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartments',
            options={'permissions': (('can_change_price', 'Can change price'),)},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'permissions': (('others_search_history', 'Can view others search history'),)},
        ),
    ]
