# Generated by Django 2.2.1 on 2019-05-11 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Apartments', '0002_auto_20190511_2046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Apartments.Apartments')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='apartment_buyer', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='User.CardDetails')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='apartment_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
