# Generated by Django 2.2.1 on 2019-05-15 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_auto_20190514_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apartments.Apartments'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.CardDetails'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
