# Generated by Django 2.2.1 on 2019-05-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='save',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
